[package]
name = "diesel_mate"
version = "0.1.0"
authors = ["AbrarNitk <abrar.nitk@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "diesel_mate_derive",
    "examples",
    "encrypted_id"
]

[dependencies]
