[package]
name = "diesel_default"
version = "0.1.0"
authors = ["AbrarNitk <abrar.nitk@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "diesel_default_derive",
    "examples"
]

[dependencies]
